[default]

weatherapi_location_name = "London"

[dev]

# weatherapi_location_name = "<your location>"

[rc]

# weatherapi_location_name = "<your location>"

[prod]

# weatherapi_location_name = "<your location>"
