[project]
name = "depends"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "redjax", email = "no@none.com" }
]
requires-python = ">=3.11"
dependencies = [
    "core-utils",
    "database",
    "settings",
]

[project.scripts]
depends = "depends:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
database = { workspace = true }
settings = { workspace = true }
core-utils = { workspace = true }
