[default]

celery_broker_password = ""
celery_backend_password = ""

[dev]

# celery_broker_password = "<your broker's password>"
# celery_backend_password = "<your backend's password>"

[rc]

# celery_broker_password = "<your broker's password>"
# celery_backend_password = "<your backend's password>"

[prod]

# celery_broker_password = "<your broker's password>"
# celery_backend_password = "<your backend's password>"
