[default]

celery_broker_host = "localhost"
celery_broker_port = 5672
celery_broker_username = "guest"
celery_broker_vhost = "/"
celery_backend_host = "localhost"
celery_backend_port = 6379

[dev]

# celery_broker_host = "localhost"
# celery_broker_port = 5672
# celery_broker_username = "rabbitmq"
# celery_broker_vhost = "/"
# celery_backend_host = "localhost"
# celery_backend_port = 6379

[rc]

[prod]
