[project]
name = "scheduling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "redjax", email = "no@none.com" }
]
requires-python = ">=3.11"
dependencies = [
    "celery>=5.4.0",
    "dramatiq[all]>=1.17.1",
    "psycopg2-binary>=2.9.10",
    "redis>=5.2.1",
    "sqlalchemy>=2.0.36",
]

[project.scripts]
scheduling = "scheduling:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
