[project]
name = "settings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "redjax", email = "no@none.com" }
]
requires-python = ">=3.11"
dependencies = [
    "dynaconf>=3.2.6",
    "loguru>=0.7.3",
]

[project.scripts]
settings = "settings:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
