[default]

dramatiq_rabbitmq_password = ""
dramatiq_redis_password = ""

[dev]

# dramatiq_rabbitmq_password = ""
# dramatiq_redis_password = ""

[rc]

# dramatiq_rabbitmq_password = ""
# dramatiq_redis_password = ""

[prod]

# dramatiq_rabbitmq_password = ""
# dramatiq_redis_password = ""
