---
volumes:
  redis_data:

networks:
  weatherdata_devnet:

services:
  redis:
    image: redis:alpine
    container_name: weatherdata_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-redis}"]
    env_file:
      - ./envs/dev.messaging.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    volumes:
      - ${REDIS_DATA_DIR:-redis_data}:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - weatherdata_devnet
