[project]
name = "http-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "redjax", email = "no@none.com" }
]
requires-python = ">=3.11"
dependencies = [
    "domain",
    "dynaconf>=3.2.6",
    "hishel>=0.1.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]

[project.scripts]
http-lib = "http_lib:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
domain = { workspace = true }
